import {useEffect,useMemo,useState} from 'react';
import {useNavigate} from 'react-router-dom';
import api from '../services/api';
import {Page,Card,Button,Input,Select,Badge,Modal,Empty} from '../components/UI';
import {CheckCircle2,ClipboardList,XCircle,Eye,ExternalLink,FileText,UserRound,Phone,Mail,MapPin,GraduationCap,UsersRound,CalendarDays,X,ZoomIn} from 'lucide-react';

const pretty=s=>String(s||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const isPdf=d=>d?.file?.format==='pdf'||/\.pdf$/i.test(d?.file?.originalName||'');
const docUrl=d=>d?.file?.previewUrl||d?.file?.url||'';

export default function AdmissionRequests(){
  const nav=useNavigate();
  const[rows,setRows]=useState([]),[q,setQ]=useState(''),[status,setStatus]=useState('pending'),[selected,setSelected]=useState(null),[rooms,setRooms]=useState([]),[beds,setBeds]=useState([]),[bedId,setBedId]=useState(''),[fee,setFee]=useState(''),[admissionDate,setAdmissionDate]=useState(new Date().toISOString().slice(0,10)),[busy,setBusy]=useState(false),[error,setError]=useState(''),[preview,setPreview]=useState(null);
  const load=()=>api.get('/admission-requests',{params:{status:status==='all'?undefined:status,q:q||undefined}}).then(r=>setRows(r.data));
  useEffect(()=>{load().catch(e=>setError(e.response?.data?.message||e.message))},[status]);
  useEffect(()=>{api.get('/rooms/overview').then(r=>{setRooms(r.data.rooms||[]);setBeds(r.data.beds||[])}).catch(()=>{})},[]);
  useEffect(()=>{const key=e=>{if(e.key==='Escape')setPreview(null)};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[]);
  const available=useMemo(()=>beds.filter(b=>b.status==='available'&&!b.studentId),[beds]);
  async function approve(){if(!selected)return;setBusy(true);setError('');try{const{data}=await api.post(`/admission-requests/${selected._id}/approve`,{bedId:bedId||undefined,monthlyFee:Number(fee),admissionDate});setSelected(null);await load();nav(`/students/${data.studentId}`)}catch(e){setError(e.response?.data?.message||e.message)}finally{setBusy(false)}}
  async function reject(){if(!selected)return;setBusy(true);try{await api.post(`/admission-requests/${selected._id}/reject`,{reason:'Rejected by hostel owner'});setSelected(null);await load()}catch(e){setError(e.response?.data?.message||e.message)}finally{setBusy(false)}}
  const openRequest=r=>{setSelected(r);setFee('');setBedId('');setAdmissionDate((r.requestedMoveInDate||new Date().toISOString()).slice(0,10))};
  const canApprove=fee!==''&&Number(fee)>=0&&!!admissionDate;

  return <Page title="Admission Requests" subtitle="Review student identity, documents and admission details before approval.">
    <div className="mb-5 grid gap-3 sm:grid-cols-[minmax(0,1fr)_180px_auto]"><Input placeholder="Search name, phone or application ID" value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()}/><Select value={status} onChange={e=>setStatus(e.target.value)}><option value="pending">Pending</option><option value="under_review">Under Review</option><option value="approved">Approved</option><option value="rejected">Rejected</option><option value="all">All</option></Select><Button onClick={load}>Search</Button></div>
    {error&&<div className="mb-4 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}
    <div className="space-y-3">{rows.length?rows.map(r=><Card key={r._id}><div className="flex flex-col gap-4 sm:flex-row sm:items-center">{r.photo?.url?<img src={r.photo.url} alt="" className="h-12 w-12 shrink-0 rounded-xl object-cover object-top"/>:<div className="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-sarva-primarySoft text-sarva-primary"><ClipboardList size={19}/></div>}<div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><b className="text-sarva-text">{r.name}</b><Badge tone={r.status==='approved'?'success':r.status==='rejected'?'danger':'warning'}>{r.status.replace('_',' ')}</Badge></div><div className="mt-1 break-words text-xs text-sarva-muted">{r.phone} · {r.publicApplicationId} · {new Date(r.createdAt).toLocaleDateString()}</div>{r.preferredRoomType&&<div className="mt-1 text-xs text-sarva-muted">Preferred: {r.preferredRoomType}</div>}</div><Button variant="ghost" onClick={()=>openRequest(r)}><Eye size={16}/> View Request</Button></div></Card>):<Empty>No admission requests found.</Empty>}</div>

    <Modal open={!!selected} onClose={()=>!busy&&setSelected(null)} title="Student Admission Review" wide>
      {selected&&<div className="pb-20 sm:pb-0">
        <div className="mb-5 flex flex-col gap-4 rounded-2xl border border-sarva-border bg-gradient-to-br from-white to-sarva-bg p-4 sm:flex-row sm:items-center">
          {selected.photo?.url?<button type="button" onClick={()=>setPreview({url:selected.photo.url,label:'Profile photo',image:true})} className="group relative h-24 w-24 shrink-0 overflow-hidden rounded-2xl border border-sarva-border bg-white"><img src={selected.photo.url} alt={selected.name} className="h-full w-full object-cover object-top"/><span className="absolute inset-0 hidden place-items-center bg-black/35 text-white group-hover:grid"><ZoomIn size={20}/></span></button>:<div className="grid h-24 w-24 shrink-0 place-items-center rounded-2xl bg-sarva-primarySoft text-sarva-primary"><UserRound size={34}/></div>}
          <div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-xl font-bold text-sarva-text">{selected.name}</h2><Badge tone={selected.status==='approved'?'success':selected.status==='rejected'?'danger':'warning'}>{pretty(selected.status)}</Badge></div><p className="mt-1 break-all text-xs font-medium text-sarva-muted">{selected.publicApplicationId}</p><div className="mt-3 flex flex-wrap gap-x-4 gap-y-2 text-sm text-sarva-muted"><span className="flex items-center gap-1.5"><Phone size={14}/>{selected.phone}</span>{selected.email&&<span className="flex min-w-0 items-center gap-1.5 break-all"><Mail size={14}/>{selected.email}</span>}</div></div>
        </div>

        <div className="grid gap-5 lg:grid-cols-[minmax(0,1.25fr)_minmax(300px,.75fr)]">
          <div className="space-y-5">
            <ReviewSection title="Personal information" icon={UserRound}><Info k="Full name" v={selected.name}/><Info k="Phone" v={selected.phone}/><Info k="Email" v={selected.email}/><Info k="Date of birth" v={selected.dob?new Date(selected.dob).toLocaleDateString():'—'}/><Info k="Gender" v={pretty(selected.gender)}/><Info k="Permanent address" v={selected.address?.permanent}/><Info k="Current address" v={selected.address?.current}/></ReviewSection>
            <ReviewSection title="Guardian / emergency contact" icon={UsersRound}><Info k="Guardian name" v={selected.guardian?.name}/><Info k="Relationship" v={selected.guardian?.relation}/><Info k="Guardian phone" v={selected.guardian?.phone}/></ReviewSection>
            <ReviewSection title="Study & hostel request" icon={GraduationCap}><Info k="Institution" v={selected.academic?.institution}/><Info k="Course" v={selected.academic?.course}/><Info k="Year" v={selected.academic?.year}/><Info k="Preferred room" v={selected.preferredRoomType}/><Info k="Requested move-in" v={selected.requestedMoveInDate?new Date(selected.requestedMoveInDate).toLocaleDateString():'—'}/>{selected.note&&<Info k="Student note" v={selected.note}/>}</ReviewSection>
          </div>

          <div className="space-y-5 lg:sticky lg:top-4 lg:self-start">
            <section className="rounded-2xl border border-sarva-border bg-white p-4 shadow-sm"><div className="mb-3 flex items-center justify-between"><h3 className="font-bold text-sarva-text">Documents & verification</h3><span className="text-xs font-semibold text-sarva-muted">{selected.documents?.length||0} files</span></div>
              {selected.documents?.length?<div className="space-y-3">{selected.documents.map((d,i)=><DocumentCard key={d._id||i} doc={d} onPreview={()=>setPreview({url:docUrl(d),label:d.label||pretty(d.type),image:!isPdf(d)})}/>)}</div>:<div className="rounded-xl bg-sarva-bg p-4 text-sm text-sarva-muted">No documents were submitted.</div>}
            </section>
            {['pending','under_review'].includes(selected.status)&&<section className="rounded-2xl border border-sarva-border bg-white p-4 shadow-sm"><div className="mb-4"><h3 className="font-bold text-sarva-text">Admission setup</h3><p className="mt-1 text-xs leading-5 text-sarva-muted">Confirm rent and admission details before creating the student record.</p></div><div className="grid gap-3"><label className="grid gap-1 text-sm font-medium">Monthly rent *<Input type="number" min="0" value={fee} onChange={e=>setFee(e.target.value)}/></label><label className="grid gap-1 text-sm font-medium">Admission date *<Input type="date" value={admissionDate} onChange={e=>setAdmissionDate(e.target.value)}/></label><label className="grid gap-1 text-sm font-medium">Assign available bed <span className="text-xs font-normal text-sarva-muted">(optional)</span><Select value={bedId} onChange={e=>setBedId(e.target.value)}><option value="">No bed yet</option>{available.map(b=>{const room=rooms.find(r=>r._id===(b.roomId?._id||b.roomId));return <option key={b._id} value={b._id}>{room?.name||'Room'} · Bed {b.label}</option>})}</Select></label></div>{!canApprove&&<p className="mt-3 rounded-xl bg-amber-50 p-3 text-xs text-amber-800">Enter the monthly rent and admission date to enable approval.</p>}<div className="mt-4 hidden gap-2 sm:flex sm:justify-end"><Button variant="danger" disabled={busy} onClick={reject}><XCircle size={16}/> Reject</Button><Button loading={busy} disabled={!canApprove} onClick={approve}><CheckCircle2 size={16}/> Approve Student</Button></div></section>}
          </div>
        </div>

        {['pending','under_review'].includes(selected.status)&&<div className="fixed inset-x-0 bottom-0 z-40 flex gap-2 border-t border-sarva-border bg-white/95 p-3 shadow-[0_-8px_30px_rgba(0,0,0,.08)] backdrop-blur sm:hidden"><Button variant="danger" disabled={busy} onClick={reject} className="flex-1"><XCircle size={16}/> Reject</Button><Button loading={busy} disabled={!canApprove} onClick={approve} className="flex-1"><CheckCircle2 size={16}/> Approve</Button></div>}
      </div>}
    </Modal>

    {preview&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/80 p-3 sm:p-6" role="dialog" aria-modal="true" aria-label={preview.label} onClick={()=>setPreview(null)}><div className="flex h-full max-h-[92vh] w-full max-w-5xl flex-col overflow-hidden rounded-2xl bg-white shadow-2xl" onClick={e=>e.stopPropagation()}><div className="flex items-center gap-3 border-b border-sarva-border p-3 sm:p-4"><div className="min-w-0 flex-1"><div className="truncate font-bold text-sarva-text">{preview.label}</div><div className="text-xs text-sarva-muted">Document preview</div></div><a href={preview.url} target="_blank" rel="noreferrer" className="inline-flex h-10 items-center gap-2 rounded-xl border border-sarva-border px-3 text-sm font-semibold text-sarva-primary"><ExternalLink size={15}/><span className="hidden sm:inline">Open original</span></a><button type="button" onClick={()=>setPreview(null)} className="grid h-10 w-10 place-items-center rounded-xl bg-sarva-bg text-sarva-text" aria-label="Close preview"><X size={18}/></button></div><div className="min-h-0 flex-1 overflow-auto bg-slate-100 p-2 sm:p-4">{preview.image?<img src={preview.url} alt={preview.label} className="mx-auto max-h-full max-w-full rounded-lg object-contain shadow-sm"/>:<iframe src={preview.url} title={preview.label} className="h-full min-h-[65vh] w-full rounded-lg bg-white"/>}</div></div></div>}
  </Page>
}

function ReviewSection({title,icon:Icon,children}){return <section className="rounded-2xl border border-sarva-border bg-white p-4 shadow-sm"><div className="mb-4 flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-lg bg-sarva-primarySoft text-sarva-primary"><Icon size={16}/></span><h3 className="font-bold text-sarva-text">{title}</h3></div><div className="grid gap-x-6 gap-y-4 sm:grid-cols-2">{children}</div></section>}
function Info({k,v}){return <div className="min-w-0"><div className="text-[10px] font-semibold uppercase tracking-wider text-sarva-muted">{k}</div><div className="mt-1 break-words text-sm font-medium text-sarva-text">{v||'—'}</div></div>}
function DocumentCard({doc,onPreview}){const url=docUrl(doc),pdf=isPdf(doc);return <div className="overflow-hidden rounded-xl border border-sarva-border bg-sarva-bg"><button type="button" onClick={onPreview} disabled={!url} className="group block w-full text-left disabled:cursor-not-allowed"><div className="relative flex h-36 items-center justify-center overflow-hidden bg-white">{url&&!pdf?<img src={url} alt="" className="h-full w-full object-cover transition duration-200 group-hover:scale-[1.02]"/>:<div className="grid place-items-center text-sarva-primary"><FileText size={38}/><span className="mt-2 text-xs font-bold">{pdf?'PDF':'FILE'}</span></div>}<span className="absolute right-2 top-2 rounded-full bg-white/95 px-2 py-1 text-[10px] font-bold uppercase tracking-wider text-sarva-primary shadow">{['front','back'].includes(doc.side)?doc.side:pretty(doc.type)}</span>{url&&<span className="absolute inset-x-2 bottom-2 flex items-center justify-center gap-1 rounded-lg bg-black/65 px-2 py-1.5 text-xs font-semibold text-white opacity-100 sm:opacity-0 sm:transition sm:group-hover:opacity-100"><Eye size={13}/> Preview</span>}</div><div className="p-3"><div className="truncate text-sm font-bold text-sarva-text">{doc.label||pretty(doc.type)}</div><div className="mt-1 truncate text-xs text-sarva-muted">{doc.file?.originalName||'Submitted document'}</div></div></button></div>}
