import {useCallback,useEffect,useMemo,useState} from 'react';
import {useNavigate} from 'react-router-dom';
import api from '../services/api';
import {Page,Card,StatCard,Badge,Button,Input,Select,Modal,money} from '../components/UI';
import {CalendarDays,ChevronLeft,ChevronRight,Wallet,ReceiptText,AlertTriangle,Plus,CheckCircle2,Clock3} from 'lucide-react';

const tone={paid:'success',due:'warning',partial:'warning',overdue:'danger',scheduled:'muted'};
const week=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];
export default function Calendar(){
 const nav=useNavigate();const [data,setData]=useState(null);const [calendar,setCalendar]=useState(null);const [cursor,setCursor]=useState(null);const [selected,setSelected]=useState(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [eventOpen,setEventOpen]=useState(false);const [event,setEvent]=useState({title:'',category:'important',amount:'',description:''});
 const load=useCallback(async(nextCalendar=calendar,nextCursor=cursor)=>{setLoading(true);setError('');try{let params={};if(nextCalendar)params.calendar=nextCalendar;if(nextCursor){params.year=nextCursor.year;params.month=nextCursor.month}const{data:r}=await api.get('/calendar/month',{params});setData(r);setCalendar(r.calendar);setCursor({year:r.year,month:r.month})}catch(e){setError(e.response?.data?.message||e.message)}finally{setLoading(false)}},[calendar,cursor]);
 useEffect(()=>{void load()},[]);
 const move=delta=>{if(!cursor)return;let y=cursor.year,m=cursor.month+delta;if(m<1){m=12;y--}if(m>12){m=1;y++}void load(calendar,{year:y,month:m})};
 const switchCalendar=async c=>{setCursor(null);setCalendar(c);await load(c,null)};
 const day=useMemo(()=>selected&&data?.days.find(d=>d.key===selected),[selected,data]);
 const saveEvent=async()=>{if(!selected||!event.title.trim())return;await api.post('/calendar/events',{...event,date:selected,calendarSystem:calendar,amount:Number(event.amount)||0});setEventOpen(false);setEvent({title:'',category:'important',amount:'',description:''});await load();};
 return <Page title="Smart Calendar" subtitle="Payments, expenses and important hostel dates in one financial timeline." actions={<div className="flex rounded-full border border-sarva-border bg-white p-1"><button onClick={()=>switchCalendar('BS')} className={`rounded-full px-3 py-1.5 text-xs font-semibold ${calendar==='BS'?'bg-sarva-primary text-white':'text-sarva-muted'}`}>नेपाली BS</button><button onClick={()=>switchCalendar('AD')} className={`rounded-full px-3 py-1.5 text-xs font-semibold ${calendar==='AD'?'bg-sarva-primary text-white':'text-sarva-muted'}`}>English AD</button></div>}>
  {error&&<Card><div className="text-sm text-sarva-danger">{error}</div></Card>}
  {loading&&!data?<div className="skeleton h-[32rem] rounded-[1.75rem]"/>:data&&<>
   <div className="sarva-mobile-safe-grid grid grid-cols-2 gap-3 lg:grid-cols-5">
    <StatCard label="Expected" value={money(data.summary.expected,data.currency)} icon={CalendarDays} tone="primary"/>
    <StatCard label="Collected" value={money(data.summary.collected,data.currency)} icon={Wallet} tone="success"/>
    <StatCard label="Outstanding" value={money(data.summary.outstanding,data.currency)} icon={AlertTriangle} tone="warning"/>
    <StatCard label="Expenses" value={money(data.summary.expenses,data.currency)} icon={ReceiptText} tone="gold"/>
    <StatCard label="Net Cash" value={money(data.summary.net,data.currency)} icon={Wallet} tone="primary"/>
   </div>
   <Card className="mt-5 overflow-hidden">
    <div className="mb-4 flex items-center justify-between gap-2"><button onClick={()=>move(-1)} className="rounded-xl border border-sarva-border p-2 text-sarva-muted" aria-label="Previous month"><ChevronLeft size={18}/></button><div className="min-w-0 text-center"><div className="truncate font-display text-lg font-semibold text-sarva-text">{data.title}</div><div className="truncate text-xs text-sarva-muted">{data.subtitle}</div></div><button onClick={()=>move(1)} className="rounded-xl border border-sarva-border p-2 text-sarva-muted" aria-label="Next month"><ChevronRight size={18}/></button></div>
    <div className="grid grid-cols-7 border-l border-t border-sarva-border">{week.map(w=><div key={w} className="border-b border-r border-sarva-border bg-sarva-bg px-1 py-2 text-center text-[10px] font-semibold uppercase text-sarva-muted">{w}</div>)}
     {data.days.map(d=>{const count=d.data.payments.length,paid=d.data.payments.filter(x=>x.status==='paid').length,overdue=d.data.payments.some(x=>x.status==='overdue');return <button key={`${d.key}-${d.day}`} onClick={()=>setSelected(d.key)} className={`sarva-calendar-cell min-h-[76px] border-b border-r border-sarva-border p-1.5 text-left align-top transition hover:bg-sarva-primarySoft/30 sm:min-h-[108px] sm:p-2 ${d.outside?'bg-sarva-bg/60 text-sarva-muted':'bg-white'}`}><div className="flex items-center justify-between"><span className={`text-xs font-semibold ${d.outside?'text-sarva-muted':'text-sarva-text'}`}>{d.day}</span>{paid>0&&<CheckCircle2 size={12} className="text-emerald-600"/>}</div><div className="mt-1 space-y-1">{count>0&&<div className={`truncate rounded-md px-1.5 py-1 text-[9px] font-semibold sm:text-[10px] ${overdue?'bg-red-50 text-red-700':'bg-amber-50 text-amber-700'}`}>{count} payment{count===1?'':'s'}</div>}{d.data.expenses.length>0&&<div className="truncate rounded-md bg-rose-50 px-1.5 py-1 text-[9px] font-semibold text-rose-700 sm:text-[10px]">{d.data.expenses.length} expense{d.data.expenses.length===1?'':'s'}</div>}{d.data.events.length>0&&<div className="truncate rounded-md bg-violet-50 px-1.5 py-1 text-[9px] font-semibold text-violet-700 sm:text-[10px]">{d.data.events.length} important</div>}</div></button>})}
    </div>
   </Card>
  </>}
  <Modal open={!!selected} onClose={()=>setSelected(null)} title={selected||'Day details'}>
   {day&&<div className="space-y-5"><div className="flex gap-2"><Button onClick={()=>setEventOpen(true)}><Plus size={15}/> Important event</Button></div>
    <section><div className="mb-2 text-xs font-semibold uppercase tracking-wider text-sarva-muted">Payments</div>{day.data.payments.length?day.data.payments.map(p=><button key={`${p.kind}-${p.invoiceId||p.studentId}`} onClick={()=>nav('/payments')} className="mb-2 flex w-full items-center gap-3 rounded-2xl border border-sarva-border p-3 text-left"><div className="min-w-0 flex-1"><div className="truncate text-sm font-semibold text-sarva-text">{p.name}</div><div className="text-xs text-sarva-muted">{p.studentCode||'Student'} · {money(p.amount,data.currency)}</div></div><Badge tone={tone[p.status]||'muted'}>{p.status}</Badge></button>):<div className="text-sm text-sarva-muted">No payments scheduled for this day.</div>}</section>
    <section><div className="mb-2 text-xs font-semibold uppercase tracking-wider text-sarva-muted">Expenses</div>{day.data.expenses.length?day.data.expenses.map(x=><div key={x._id} className="mb-2 flex items-center justify-between rounded-2xl bg-sarva-bg p-3"><div><div className="text-sm font-semibold text-sarva-text">{x.description||x.category||'Expense'}</div><div className="text-xs text-sarva-muted">{x.category||'Expense'}</div></div><div className="font-semibold text-sarva-text">{money(x.amount,data.currency)}</div></div>):<div className="text-sm text-sarva-muted">No expenses recorded.</div>}</section>
    <section><div className="mb-2 text-xs font-semibold uppercase tracking-wider text-sarva-muted">Important</div>{day.data.events.length?day.data.events.map(x=><div key={x._id} className="mb-2 rounded-2xl bg-violet-50 p-3"><div className="text-sm font-semibold text-sarva-text">{x.title}</div>{x.description&&<div className="mt-1 text-xs text-sarva-muted">{x.description}</div>}</div>):<div className="text-sm text-sarva-muted">No important events.</div>}</section>
    <div className="grid grid-cols-2 gap-2 rounded-2xl bg-sarva-bg p-3 text-xs"><div>Expected<br/><b>{money(day.data.expected,data.currency)}</b></div><div>Collected<br/><b>{money(day.data.collected,data.currency)}</b></div><div>Expenses<br/><b>{money(day.data.expensesTotal,data.currency)}</b></div><div>Net cash<br/><b>{money(day.data.collected-day.data.expensesTotal,data.currency)}</b></div></div>
   </div>}
  </Modal>
  <Modal open={eventOpen} onClose={()=>setEventOpen(false)} title="Add important event"><div className="space-y-3"><Input value={event.title} onChange={e=>setEvent(v=>({...v,title:e.target.value}))} placeholder="Event title"/><Select value={event.category} onChange={e=>setEvent(v=>({...v,category:e.target.value}))}><option value="important">Important</option><option value="rent">Rent</option><option value="utility">Utility</option><option value="salary">Salary</option><option value="maintenance">Maintenance</option><option value="meeting">Meeting</option><option value="holiday">Holiday</option><option value="other">Other</option></Select><Input type="number" min="0" value={event.amount} onChange={e=>setEvent(v=>({...v,amount:e.target.value}))} placeholder="Optional amount"/><Input value={event.description} onChange={e=>setEvent(v=>({...v,description:e.target.value}))} placeholder="Description"/><Button onClick={saveEvent} disabled={!event.title.trim()}>Save event</Button></div></Modal>
 </Page>
}
