const express=require('express');
const mongoose=require('mongoose');
const {Student,Room,Bed,RoomAssignment,Invoice,Payment,PaymentAllocation,CreditTransaction,Expense,StockItem,StockTransaction,Attendance,Staff,Salary,Notification,NotificationLog,AuditLog}=require('../models');
const {auth,ownerOnly}=require('../middleware/auth');
const requireCap=require('../middleware/capability');
const {sendEmail}=require('../services/email');
const router=express.Router();
const num=v=>Number(v?.toString?.()??v??0);
const money=v=>Math.round(Number(v)*100)/100;
const methods=new Set(['cash','manual_qr','esewa','other']);
const audit=(req,action,entity,entityId,meta={})=>AuditLog.create({hostelId:req.hostel._id,actorId:req.user._id,actorRole:req.user.role,action,entity,entityId,meta});

router.get('/payments',auth,ownerOnly,requireCap('payments'),async(req,res,next)=>{try{const q={hostelId:req.hostel._id};if(req.query.studentId)q.studentId=req.query.studentId;const rows=await Payment.find(q).populate('studentId','name studentCode phone').populate('invoiceId','periodKey total balance status').sort({createdAt:-1}).limit(Math.min(Number(req.query.limit)||200,500));res.json(rows)}catch(e){next(e)}});
router.post('/payments/split',auth,ownerOnly,requireCap('payments'),async(req,res)=>{const session=await mongoose.startSession();try{let out;await session.withTransaction(async()=>{const student=await Student.findOne({_id:req.body.studentId,hostelId:req.hostel._id}).session(session);if(!student)throw Object.assign(new Error('Student not found'),{status:404});const tenders=Array.isArray(req.body.tenders)?req.body.tenders:[];if(!tenders.length)throw Object.assign(new Error('At least one payment tender is required'),{status:400});for(const t of tenders){if(!methods.has(t.method)||!(Number(t.amount)>0))throw Object.assign(new Error('Invalid payment tender'),{status:400})}let remaining=tenders.reduce((s,t)=>s+Number(t.amount),0);const invoices=await Invoice.find({hostelId:req.hostel._id,studentId:student._id,status:{$in:['open','partial','overdue']},balance:{$gt:0}}).sort({dueDate:1,createdAt:1}).session(session);const due=invoices.reduce((s,i)=>s+num(i.balance),0);if(remaining>due+0.001)throw Object.assign(new Error('Payment exceeds outstanding balance'),{status:400});const created=[];for(const tender of tenders){let tenderLeft=Number(tender.amount);const p=(await Payment.create([{hostelId:req.hostel._id,studentId:student._id,currency:req.hostel.currency,amount:tenderLeft,method:tender.method,reference:tender.reference,notes:req.body.notes,createdBy:req.user._id}],{session}))[0];for(const inv of invoices){if(tenderLeft<=0)break;const bal=num(inv.balance);if(bal<=0)continue;const allocated=Math.min(tenderLeft,bal);await PaymentAllocation.create([{hostelId:req.hostel._id,paymentId:p._id,invoiceId:inv._id,studentId:student._id,amount:allocated,currency:inv.currency}],{session});inv.paid=money(num(inv.paid)+allocated);inv.balance=money(num(inv.total)-num(inv.paid));inv.status=num(inv.balance)<=0?'paid':'partial';await inv.save({session});tenderLeft=money(tenderLeft-allocated)}created.push(p)}await AuditLog.create([{hostelId:req.hostel._id,actorId:req.user._id,actorRole:req.user.role,action:'payment.split',entity:'Student',entityId:student._id,meta:{tenders:tenders.map(t=>({method:t.method,amount:t.amount})),total:remaining}}],{session});out={payments:created,total:remaining,remainingOutstanding:money(due-remaining)}});res.status(201).json(out)}catch(e){res.status(e.status||500).json({message:e.message})}finally{await session.endSession()}});
router.get('/payments/:id/receipt',auth,async(req,res,next)=>{try{const p=await Payment.findOne({_id:req.params.id,hostelId:req.hostel._id}).populate('studentId','name studentCode phone');if(!p)return res.sendStatus(404);const allocations=await PaymentAllocation.find({hostelId:req.hostel._id,paymentId:p._id}).populate('invoiceId','periodKey total balance');res.json({receiptNumber:`SRV-${String(p._id).slice(-8).toUpperCase()}`,hostel:{name:req.hostel.name,address:req.hostel.contact?.address,phone:req.hostel.contact?.phone,currency:req.hostel.currency},payment:p,allocations})}catch(e){next(e)}});

router.get('/rooms/overview',auth,ownerOnly,requireCap('rooms'),async(req,res,next)=>{try{const [rooms,beds,assignments]=await Promise.all([Room.find({hostelId:req.hostel._id}).sort({building:1,floor:1,name:1}),Bed.find({hostelId:req.hostel._id}).populate('studentId','name studentCode photo phone'),RoomAssignment.find({hostelId:req.hostel._id,active:true}).populate('studentId','name studentCode photo phone').populate('roomId','name building floor').populate('bedId','label')]);res.json({rooms,beds,assignments})}catch(e){next(e)}});
router.post('/rooms/:roomId/beds',auth,ownerOnly,requireCap('rooms'),async(req,res,next)=>{try{const room=await Room.findOne({_id:req.params.roomId,hostelId:req.hostel._id});if(!room)return res.sendStatus(404);const label=String(req.body.label||'').trim();if(!label)return res.status(400).json({message:'Bed number is required'});if(await Bed.exists({hostelId:req.hostel._id,roomId:room._id,label}))return res.status(409).json({message:'Bed already exists in this room'});const bed=await Bed.create({hostelId:req.hostel._id,roomId:room._id,label,price:req.body.price||room.price,status:'available'});res.status(201).json(bed)}catch(e){next(e)}});
router.post('/rooms/assign',auth,ownerOnly,requireCap('rooms'),async(req,res)=>{const session=await mongoose.startSession();try{let out;await session.withTransaction(async()=>{const student=await Student.findOne({_id:req.body.studentId,hostelId:req.hostel._id,status:{$ne:'checked_out'}}).session(session);if(!student)throw Object.assign(new Error('Student not found or checked out'),{status:404});if(await RoomAssignment.exists({hostelId:req.hostel._id,studentId:student._id,active:true}).session(session))throw Object.assign(new Error('Student already has an active bed assignment'),{status:409});const bed=await Bed.findOneAndUpdate({_id:req.body.bedId,hostelId:req.hostel._id,status:'available',studentId:null},{$set:{status:'occupied',studentId:student._id}},{new:true,session});if(!bed)throw Object.assign(new Error('Bed is no longer available'),{status:409});const room=await Room.findOne({_id:bed.roomId,hostelId:req.hostel._id}).session(session);if(!room)throw Object.assign(new Error('Room not found'),{status:404});out=(await RoomAssignment.create([{hostelId:req.hostel._id,studentId:student._id,roomId:room._id,bedId:bed._id,startDate:new Date(),active:true,reason:req.body.reason||'Initial assignment',createdBy:req.user._id}],{session}))[0]});await audit(req,'room.assign','RoomAssignment',out._id);res.status(201).json(out)}catch(e){const duplicate=e?.code===11000;res.status(duplicate?409:(e.status||500)).json({success:false,message:duplicate?'Bed or student already has an active assignment':e.message,code:duplicate?'ASSIGNMENT_CONFLICT':undefined})}finally{await session.endSession()}});
router.post('/rooms/transfer',auth,ownerOnly,requireCap('rooms'),async(req,res)=>{const session=await mongoose.startSession();try{let out;await session.withTransaction(async()=>{const current=await RoomAssignment.findOne({hostelId:req.hostel._id,studentId:req.body.studentId,active:true}).session(session);if(!current)throw Object.assign(new Error('Active room assignment not found'),{status:404});const nextBed=await Bed.findOneAndUpdate({_id:req.body.bedId,hostelId:req.hostel._id,status:'available',studentId:null},{$set:{status:'occupied',studentId:req.body.studentId}},{new:true,session});if(!nextBed)throw Object.assign(new Error('New bed is no longer available'),{status:409});const reason=String(req.body.reason||'').trim();if(!reason)throw Object.assign(new Error('Transfer reason is required'),{status:400});const oldBed=await Bed.findOne({_id:current.bedId,hostelId:req.hostel._id}).session(session);current.active=false;current.endDate=new Date();current.endReason=reason;await current.save({session});if(oldBed){oldBed.status='available';oldBed.studentId=null;await oldBed.save({session})}const nextRoom=await Room.findOne({_id:nextBed.roomId,hostelId:req.hostel._id}).session(session);out=(await RoomAssignment.create([{hostelId:req.hostel._id,studentId:req.body.studentId,roomId:nextRoom._id,bedId:nextBed._id,startDate:new Date(),active:true,reason,createdBy:req.user._id}],{session}))[0]});await audit(req,'room.transfer','RoomAssignment',out._id,{reason:req.body.reason});res.status(201).json(out)}catch(e){res.status(e.status||500).json({message:e.message})}finally{await session.endSession()}});

router.get('/attendance/day',auth,ownerOnly,requireCap('attendance'),async(req,res,next)=>{try{const date=new Date(req.query.date||Date.now());const start=new Date(date);start.setHours(0,0,0,0);const end=new Date(start);end.setDate(end.getDate()+1);const [students,rows]=await Promise.all([Student.find({hostelId:req.hostel._id,status:'active'}).select('name studentCode'),Attendance.find({hostelId:req.hostel._id,date:{$gte:start,$lt:end}})]);const map=new Map(rows.map(x=>[String(x.studentId),x]));res.json(students.map(s=>({student:s,attendance:map.get(String(s._id))||null})))}catch(e){next(e)}});
router.put('/attendance/:studentId/day',auth,ownerOnly,requireCap('attendance'),async(req,res,next)=>{try{const date=new Date(req.body.date||Date.now());date.setHours(0,0,0,0);if(!['present','absent','leave','late'].includes(req.body.status))return res.status(400).json({message:'Invalid attendance status'});const row=await Attendance.findOneAndUpdate({hostelId:req.hostel._id,studentId:req.params.studentId,date},{$set:{status:req.body.status,method:req.body.method||'manual',entryAt:req.body.entryAt||undefined,exitAt:req.body.exitAt||undefined,note:req.body.note||''}},{new:true,upsert:true,setDefaultsOnInsert:true});res.json(row)}catch(e){next(e)}});

router.get('/salaries',auth,ownerOnly,requireCap('salary'),async(req,res,next)=>{try{res.json(await Salary.find({hostelId:req.hostel._id}).populate('staffId','name role phone').sort({periodKey:-1,createdAt:-1}))}catch(e){next(e)}});
router.post('/salaries/pay',auth,ownerOnly,requireCap('salary'),async(req,res,next)=>{try{const staff=await Staff.findOne({_id:req.body.staffId,hostelId:req.hostel._id});if(!staff)return res.sendStatus(404);const periodKey=String(req.body.periodKey||'').trim();if(!/^\d{4}-\d{2}$/.test(periodKey))return res.status(400).json({message:'Salary month must be YYYY-MM'});const base=Number(req.body.base??num(staff.monthlySalary)),bonus=Number(req.body.bonus||0),deduction=Number(req.body.deduction||0),advance=Number(req.body.advance||0),pay=Number(req.body.amount||0);const net=money(base+bonus-deduction-advance);if(pay<0||pay>net)return res.status(400).json({message:'Invalid salary payment amount'});let row=await Salary.findOne({hostelId:req.hostel._id,staffId:staff._id,periodKey});if(!row)row=new Salary({hostelId:req.hostel._id,staffId:staff._id,periodKey,currency:req.hostel.currency,base,bonus,deduction,advance,paid:0});row.paid=money(num(row.paid)+pay);row.net=net;row.remaining=money(net-num(row.paid));row.status=row.remaining<=0?'paid':num(row.paid)>0?'partial':'pending';row.method=req.body.method||'cash';row.paidAt=pay?new Date():row.paidAt;await row.save();if(req.body.createExpense&&pay>0)await Expense.create({hostelId:req.hostel._id,category:'Salary',amount:pay,currency:req.hostel.currency,date:new Date(),method:row.method,vendor:staff.name,description:`Salary ${periodKey}`,salaryId:row._id});await audit(req,'salary.pay','Salary',row._id,{amount:pay,periodKey});res.status(201).json(row)}catch(e){next(e)}});

router.post('/students/:id/checkout',auth,ownerOnly,async(req,res)=>{const session=await mongoose.startSession();try{let out;await session.withTransaction(async()=>{const student=await Student.findOne({_id:req.params.id,hostelId:req.hostel._id}).session(session);if(!student)throw Object.assign(new Error('Student not found'),{status:404});const open=await Invoice.find({hostelId:req.hostel._id,studentId:student._id,status:{$in:['open','partial','overdue']}}).session(session);const outstanding=open.reduce((s,i)=>s+num(i.balance),0);if(outstanding>0&&!req.body.force)throw Object.assign(new Error(`Student has ${req.hostel.currency} ${outstanding.toFixed(2)} outstanding. Settle it or confirm force checkout.`),{status:409});const assignment=await RoomAssignment.findOne({hostelId:req.hostel._id,studentId:student._id,active:true}).session(session);if(assignment){assignment.active=false;assignment.endDate=new Date();assignment.endReason=req.body.reason||'Student checkout';await assignment.save({session});const bed=await Bed.findOne({_id:assignment.bedId,hostelId:req.hostel._id}).session(session);if(bed){bed.status='available';bed.studentId=null;await bed.save({session})}}student.status='checked_out';student.checkoutDate=new Date();student.checkoutReason=req.body.reason||'';await student.save({session});out={student,outstanding}});await audit(req,'student.checkout','Student',req.params.id,{reason:req.body.reason,force:!!req.body.force});res.json(out)}catch(e){res.status(e.status||500).json({message:e.message})}finally{await session.endSession()}});

router.post('/broadcast',auth,ownerOnly,requireCap('broadcast'),async(req,res,next)=>{try{const ids=Array.isArray(req.body.studentIds)?req.body.studentIds:[];const q={hostelId:req.hostel._id,status:'active'};if(ids.length)q._id={$in:ids};const students=await Student.find(q).select('name email');const results=[];for(const s of students){if(!s.email)continue;const note=await Notification.create({hostelId:req.hostel._id,studentId:s._id,channel:'email',type:'broadcast',recipient:s.email,subject:req.body.subject,message:req.body.message});try{await sendEmail({to:s.email,subject:req.body.subject,text:req.body.message});note.status='sent';note.sentAt=new Date()}catch(e){note.status='failed';note.error=e.message}await note.save();await NotificationLog.create({hostelId:req.hostel._id,notificationId:note._id,studentId:s._id,status:note.status,error:note.error});results.push({studentId:s._id,status:note.status})}res.status(201).json({sent:results.filter(x=>x.status==='sent').length,failed:results.filter(x=>x.status==='failed').length,results})}catch(e){next(e)}});

router.get('/reports/:type',auth,ownerOnly,requireCap('reports'),async(req,res,next)=>{try{const h=req.hostel._id,type=req.params.type;let rows=[];if(type==='students')rows=await Student.find({hostelId:h}).select('studentCode name phone email status admissionDate monthlyFee').lean();else if(type==='payments')rows=await Payment.find({hostelId:h}).populate('studentId','name studentCode').sort({createdAt:-1}).lean();else if(type==='expenses')rows=await Expense.find({hostelId:h}).sort({date:-1}).lean();else if(type==='stock')rows=await StockItem.find({hostelId:h}).lean();else if(type==='attendance')rows=await Attendance.find({hostelId:h}).populate('studentId','name studentCode').sort({date:-1}).lean();else if(type==='salary')rows=await Salary.find({hostelId:h}).populate('staffId','name role').lean();else if(type==='occupancy')rows=await RoomAssignment.find({hostelId:h}).populate('studentId','name studentCode').populate('roomId','name building floor').populate('bedId','label').lean();else return res.status(400).json({message:'Unknown report type'});res.json({type,currency:req.hostel.currency,generatedAt:new Date(),rows})}catch(e){next(e)}});
router.get('/audit',auth,ownerOnly,async(req,res,next)=>{try{res.json(await AuditLog.find({hostelId:req.hostel._id}).sort({createdAt:-1}).limit(300))}catch(e){next(e)}});

router.get('/student-portal/me',auth,requireCap('student_portal'),async(req,res,next)=>{try{if(req.user.role!=='student')return res.status(403).json({message:'Student access required'});const student=await Student.findOne({hostelId:req.hostel._id,userId:req.user._id});if(!student)return res.status(404).json({message:'Student profile not found'});const [invoices,payments,assignment,attendance,notifications]=await Promise.all([Invoice.find({hostelId:req.hostel._id,studentId:student._id}).sort({dueDate:-1}),Payment.find({hostelId:req.hostel._id,studentId:student._id}).sort({createdAt:-1}),RoomAssignment.findOne({hostelId:req.hostel._id,studentId:student._id,active:true}).populate('roomId','name building floor').populate('bedId','label'),Attendance.find({hostelId:req.hostel._id,studentId:student._id}).sort({date:-1}).limit(31),Notification.find({hostelId:req.hostel._id,studentId:student._id}).sort({createdAt:-1}).limit(50)]);res.json({student,invoices,payments,assignment,attendance,notifications,outstanding:invoices.reduce((s,i)=>s+num(i.balance),0)})}catch(e){next(e)}});

router.get('/analytics/trend',auth,ownerOnly,requireCap('reports'),async(req,res,next)=>{try{
const h=req.hostel._id;
const since=new Date();since.setMonth(since.getMonth()-5);since.setDate(1);since.setHours(0,0,0,0);
const [billedAgg,collectedAgg,expenseAgg,methodAgg]=await Promise.all([
Invoice.aggregate([{$match:{hostelId:h,createdAt:{$gte:since}}},{$group:{_id:{$dateToString:{format:'%Y-%m',date:'$createdAt'}},total:{$sum:{$toDouble:'$total'}}}}]),
Payment.aggregate([{$match:{hostelId:h,status:'confirmed',createdAt:{$gte:since}}},{$group:{_id:{$dateToString:{format:'%Y-%m',date:'$createdAt'}},total:{$sum:{$toDouble:'$amount'}}}}]),
Expense.aggregate([{$match:{hostelId:h,date:{$gte:since}}},{$group:{_id:{$dateToString:{format:'%Y-%m',date:'$date'}},total:{$sum:{$toDouble:'$amount'}}}}]),
Payment.aggregate([{$match:{hostelId:h,status:'confirmed',createdAt:{$gte:since}}},{$group:{_id:'$method',total:{$sum:{$toDouble:'$amount'}}}}])
]);
const months=[];for(let i=5;i>=0;i--){const d=new Date();d.setMonth(d.getMonth()-i);months.push(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`)}
const pick=(arr)=>{const m=new Map(arr.map(x=>[x._id,x.total]));return months.map(k=>Math.round((m.get(k)||0)*100)/100)};
res.json({
months,
billed:pick(billedAgg),
collected:pick(collectedAgg),
expenses:pick(expenseAgg),
byMethod:methodAgg.map(x=>({method:x._id||'other',total:Math.round((x.total||0)*100)/100})),
currency:req.hostel.currency
})
}catch(e){next(e)}});

module.exports=router;
